# Generated by Django 4.1.13 on 2024-12-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=255)),
                ('date_of_distribution', models.DateField()),
                ('billing_file', models.FileField(upload_to='billing_files/')),
                ('submission_status', models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical')], max_length=50)),
                ('approval_status', models.CharField(max_length=255)),
                ('approval_amount', models.CharField(choices=[('As per norm', 'As per norm'), ('Not per norms', 'Not per norms')], max_length=50)),
                ('follow_up', models.TextField(blank=True, null=True)),
                ('reason_not_match', models.TextField(blank=True, null=True)),
                ('claim_option', models.CharField(choices=[('Claim', 'Claim'), ('Not Claim', 'Not Claim')], max_length=50)),
                ('claim_details', models.TextField(blank=True, null=True)),
                ('not_claim_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('confirmPassword', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_policy',
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
