# Generated by Django 3.2 on 2025-05-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_insurance_login_register_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daycare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissionType', models.JSONField()),
                ('patientName', models.CharField(max_length=255)),
                ('uhid', models.CharField(max_length=100)),
                ('doctorName', models.CharField(max_length=255)),
                ('companyName', models.CharField(blank=True, max_length=255, null=True)),
                ('specificInsuranceCompany', models.CharField(blank=True, max_length=255, null=True)),
                ('billType', models.CharField(max_length=50)),
                ('claimId', models.CharField(max_length=100)),
                ('opFile', models.CharField(blank=True, max_length=255, null=True)),
                ('submissionDate', models.DateField()),
                ('claimDetails', models.CharField(max_length=50)),
                ('billAmount', models.CharField(max_length=50)),
                ('claimApproval', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='claim_details',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='approval_amount',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='billing_file',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='claim_option',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='date_of_distribution',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='not_claim_reason',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='reason_not_match',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='submission_status',
        ),
        migrations.AddField(
            model_name='insurance',
            name='approval',
            field=models.CharField(default='As per norm', max_length=255),
        ),
        migrations.AddField(
            model_name='insurance',
            name='approvalAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='approvalDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='billAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='billDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='billNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='billingFile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='claimDetails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='claimOption',
            field=models.CharField(default='Not Claim', max_length=255),
        ),
        migrations.AddField(
            model_name='insurance',
            name='claimedAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='companyName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='dateOfDischarge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='editHistory',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='insurance',
            name='fileSubmissionDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='followUp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='ipNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='notClaimReason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='opNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='patient_uhid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='pendingAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='queryDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='queryResponse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='queryUpload',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='radiotherapyCycles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='reasonNotMatch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='settledAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='specificInsuranceCompany',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='submissionStatus',
            field=models.CharField(default='Online', max_length=255),
        ),
        migrations.AddField(
            model_name='insurance',
            name='treatmentType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
