# Generated by Django 3.2 on 2025-05-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20250508_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='daycare',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daycare',
            name='lastmodified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='daycare',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurance',
            name='lastmodified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='login',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='lastmodified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='register',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='lastmodified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
