# Generated by Django 3.2 on 2025-06-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_auto_20250523_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_uhid', models.CharField(max_length=50, unique=True)),
                ('mobile_number', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('treatment', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.CharField(max_length=255)),
                ('refund', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='register',
            name='confirmPassword',
        ),
        migrations.AlterField(
            model_name='daycare',
            name='billAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='daycare',
            name='billType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='daycare',
            name='claimApproval',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='daycare',
            name='claimDetails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='daycare',
            name='claimId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='daycare',
            name='submissionDate',
            field=models.CharField(max_length=150),
        ),
    ]
