# Generated by Django 3.2 on 2025-07-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20250611_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.RemoveField(
            model_name='otherrecord',
            name='amount',
        ),
        migrations.AddField(
            model_name='insurance',
            name='claimId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='payment_details',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='otherrecord',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='otherrecord',
            name='patient_uhid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='otherrecord',
            name='refund',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
