# Generated by Django 3.2 on 2026-07-17 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20250719_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemoRecord',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('chemo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('date_of_discharge', models.DateField(blank=True, null=True)),
                ('insurance_type', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_to_be_paid', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine_details', models.TextField(blank=True, null=True)),
                ('payment_details', models.JSONField(default=list)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('enquiry_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('ipNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('opNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('patientName', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('insuranceName', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment', models.CharField(blank=True, max_length=500, null=True)),
                ('specificInsuranceCompany', models.CharField(blank=True, max_length=255, null=True)),
                ('reasonForApproach', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RTRecord',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('rt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('date_of_discharge', models.DateField(blank=True, null=True)),
                ('insurance_type', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_to_be_paid', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_details', models.JSONField(default=list)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='insurance',
            name='grossAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='gst',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='netAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='referral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='taxAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='voucherNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='approved_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='final_approved_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='final_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='has_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='ip_op_type',
            field=models.CharField(blank=True, choices=[('IP', 'IP'), ('OP', 'OP')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='is_finalapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='is_refund_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='refund_approved_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='refund_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('followup_id', models.IntegerField(primary_key=True, serialize=False)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('followup_Remarks', models.TextField(blank=True, null=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='insurance.enquiry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
