# Generated by Django 3.2 on 2026-07-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_auto_20260717_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemorecord',
            name='editHistory',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='editHistory',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='rtrecord',
            name='editHistory',
            field=models.JSONField(default=list),
        ),
    ]
