# Generated by Django 3.2 on 2026-07-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_auto_20260717_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherrecord',
            name='is_refund_initiated',
            field=models.BooleanField(default=False),
        ),
    ]
