# Generated by Django 3.2 on 2026-07-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_otherrecord_is_refund_initiated'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherrecord',
            name='refund_initiated_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='refund_initiated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
