# Generated by Django 3.2 on 2026-07-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_auto_20260718_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='ctseType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
